// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8UIY9Q-Rx-nRHaRPXlWE995JQVJZaCg8',
    appId: '1:304786571106:web:f2b347a7e0673048ba363b',
    messagingSenderId: '304786571106',
    projectId: 'flutter-pokedex-b7381',
    authDomain: 'flutter-pokedex-b7381.firebaseapp.com',
    storageBucket: 'flutter-pokedex-b7381.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg5qfoKTfhpH8tB59UcNgPxj7lvXIgDqM',
    appId: '1:304786571106:android:a815214f2df8a378ba363b',
    messagingSenderId: '304786571106',
    projectId: 'flutter-pokedex-b7381',
    storageBucket: 'flutter-pokedex-b7381.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCflLRc2SGayA_hTMFYzv4U_fb_rZH_fzw',
    appId: '1:304786571106:ios:9b8a9132ca2d92aeba363b',
    messagingSenderId: '304786571106',
    projectId: 'flutter-pokedex-b7381',
    storageBucket: 'flutter-pokedex-b7381.appspot.com',
    iosClientId: '304786571106-i20fv4sk2ij136vs7k5oqaue63co0n96.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCflLRc2SGayA_hTMFYzv4U_fb_rZH_fzw',
    appId: '1:304786571106:ios:ab49b4beed8b9a0fba363b',
    messagingSenderId: '304786571106',
    projectId: 'flutter-pokedex-b7381',
    storageBucket: 'flutter-pokedex-b7381.appspot.com',
    iosClientId: '304786571106-8satvfohbohqssu3m94kgr9qvn0pi05i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedex.RunnerTests',
  );
}
